### ISSUE TITLE
⚽️ Send emails on arbitrage occasion

### ISSUE THREAD

**Issue by AdrKacz** [AdrKacz/probable-couscous#2]
> Use this task to track progress over a list of related task

**Is your feature request related to a problem? Please describe.**
I want to receive an email when there is an arbitrage. The email should include most information about the arbitrage:
- Match details (teams, date and time)
- Website where it has been seen, with links for easy access
- Odds of the match on each platform

**Tasks**
- [ ] Add a least two parsers
  - [x] #3
  - [x] #4
- [ ] Add infrastructure
  - [ ] Create Lambda functions to execute Winamax and Betclic parsers
    - [ ] Store list of matches in an S3 objet
  - [ ]  Create a Lambda function to send email
    - [ ] Follow AWS prerequisite to send emails    
  - [ ] Create Lambda function to update team names
    - [ ] Create a file in Github with team conversation for each platform
    - [ ] Create a Github Action to store the content of the file with the teams in an S3 object
    - [ ] Send emails to alert that the team file need to be updated
    - [ ] Store updated team names with match details in an S3 object
  - [ ] Create a Lambda function that reads the S3 objects to find arbitrage
    - [ ] Send email with analysis details
      - [ ] Add arbitrage found to the email if any
- [ ] Orchestrate the workflow
  - [ ] Verify manually that the workflow works from end to end
  - [ ] Create a Step Function for your workflow
    - [ ] Execute the Step Function once every hour

**Comment by AdrKacz** [comment]
Wrong repo close it
